openedx/edx-django-utils

- edx_django_utils/__init__.py
- setup.py
- tox.ini
Removing Python 3 support for now to land this.  This was edx-platform Python 2.7 code to start.  Most of the Python 3 work was completed, but there is still some left.
> ARCH-177: Python 3 support temporarily disabled.

- edx_django_utils/cache/README.rst
Provide warning for using the TieredCache with bools.
NOTE: I already committed the first version of this to master by mistake.  Feel free to add comments and I will update.  Thanks.
> Fix bool warning.

- edx_django_utils/__init__.py
- edx_django_utils/cache/README.rst
- edx_django_utils/cache/middleware.py
- edx_django_utils/cache/tests/test_middleware.py
- edx_django_utils/cache/tests/test_utils.py
Fixed documentation and test name using force_cache_miss
**JIRA:**
[WL-1914](https://openedx.atlassian.net/browse/WL-1914)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Fixed documentation and test name using force_cache_miss

- docs/conf.py
- edx_django_utils/__init__.py
- edx_django_utils/cache/__init__.py
- edx_django_utils/cache/tests/test_middleware.py
- edx_django_utils/cache/tests/test_utils.py
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/middleware.py
- edx_django_utils/monitoring/tests/test_monitoring.py
- edx_django_utils/tests/test_private_utils.py
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/doc.in
- requirements/doc.txt
- requirements/pip-tools.in
- requirements/pip-tools.txt
- requirements/quality.in
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- requirements/travis.in
- requirements/travis.txt
- setup.py
**Description:** 
This PR updates the jinja2 version. Please see PROD-343 for more information.
**JIRA:**
[PROD-343](https://openedx.atlassian.net/browse/PROD-343)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> run make upgrade to update jinja2

- .travis.yml
- edx_django_utils/__init__.py
- edx_django_utils/cache/README.rst
- edx_django_utils/cache/middleware.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/middleware.py
- edx_django_utils/private_utils.py
- requirements/base.in
- setup.py
- tox.ini
In Django 1.10, a new middleware style was introduced, that uses a MIDDLEWARE setting rather than MIDDLEWARE_CLASSES.
In Django 2, only the new style will be supported.
This change allows our middleware to be used both ways, but drops support for Django 1.8.
This package claims to support Django 2, but the current middleware classes can't work with Django 2, right? Was that ever tried?
If Django 1.8 support is important to maintain, I can do an optional import situation and keep support. But I figured the open edx ecosystem is on 1.11+.
**Reviewers:**
finished.
> Support Django 1.10 style middleware

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/utils.py
Version 5.0.0.124 of the New Relic Agent changed the function tracing
API. Using it the old way was resulting in many thousands of new metrics
being added (each process invocation of a function trace was creating a
new metric name), so we ended up with a bunch of "metrics" named like:
determine_group_permissions/<newrelic.api.web_transaction.WSGIWebTransaction object at 0x7f09bf016ad0>
determine_group_permissions/<newrelic.api.web_transaction.WSGIWebTransaction object at 0x7f09bf098510>
determine_group_permissions/<newrelic.api.web_transaction.WSGIWebTransaction object at 0x7f09bf0a8bd0>
determine_group_permissions/<newrelic.api.web_transaction.WSGIWebTransaction object at 0x7f09bf108b50>
determine_group_permissions/<newrelic.api.web_transaction.WSGIWebTransaction object at …
> Fix function tracing for New Relic Agent 5.0.0.124

- edx_django_utils/cache/README.rst
* Only a single line had a significant text change, which is clarifying that RequestCacheMiddleware is required by the TieredCache.  See https://github.com/edx/edx-django-utils/pull/29/files#r364262397
* The rest of the changes were removing hard-wraps to comply with the documentation OEP.
finished.
> clarify RequestCacheMiddleware requirement

- edx_django_utils/__init__.py
- edx_django_utils/cache/tests/test_middleware.py
- edx_django_utils/cache/tests/test_utils.py
- edx_django_utils/db/__init__.py
- edx_django_utils/db/read_replica.py
- edx_django_utils/db/tests/test_read_replica.py
- edx_django_utils/tests/test_private_utils.py
- test_settings.py
This migrates the use_read_replica_if_available and read_replica_or_default
functions from edx_platform/common/djangoapps/utils/query.py, and augments
them with a pair of context managers for asserting that particular chunks
of code are read-only (and thus read-replica safe).
Describe in a couple of sentence what this PR adds
**JIRA:**
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished. …
> Add tooling for working with the read-replica database.

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/code_owner/middleware.py
- edx_django_utils/monitoring/code_owner/tests/mock_views.py
- edx_django_utils/monitoring/code_owner/tests/test_middleware.py
- edx_django_utils/monitoring/code_owner/tests/test_utils.py
- edx_django_utils/monitoring/code_owner/utils.py
- edx_django_utils/monitoring/docs/decisions/0001-monitoring-by-code-owner.rst
- pylintrc
The CodeOwnerMetricMiddleware is being moved from
edx-platform to edx-django-utils so it can be used
in multiple IDAs. The justification for this move
is in the ADR included in this commit.
This PR also contains minimal changes, like updating
paths and comments as required.
The original implementation was here:
https://github.com/edx/edx-platform/blob/7e56d89bcccf2082a9c74d91fb44b15046f00b45/lms/djangoapps/monitoring/middleware.py#L13
The original implementation will soon be removed and
replaced with this new implementation.  See https://github.com/edx/edx-platform/pull/24508
ARCHBOM-1356
Describe in a couple of sentence what this PR adds
**JIRA:**
List dependencies on other outstanding PRs, …
> ARCHBOM-1356: move CodeOwnerMetricMiddleware to edx-django-utils

- CHANGELOG.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/code_owner/middleware.py
- edx_django_utils/monitoring/code_owner/tests/test_middleware.py
- edx_django_utils/monitoring/tests/test_monitoring.py
- edx_django_utils/monitoring/utils.py
- add get_current_transaction function which returns am
object with a name property.
- update CodeOwnerMetricMiddleware to use the current
transaction to determine the code_owner metric in cases
where resolve doesn't work.
**JIRA:**
[ARCHBOM-1283](https://openedx.atlassian.net/browse/ARCHBOM-1283)
finished.
> ARCHBOM-1283: update CodeOwnerMetricMiddleware

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/code_owner/middleware.py
- edx_django_utils/monitoring/code_owner/tests/test_middleware.py
- edx_django_utils/monitoring/code_owner/utils.py
Added a catch-all capability to CodeOwnerMetricMiddleware
when CODE_OWNER_MAPPINGS includes a '*' as a team's
module. The catch-all is used only if there is no other
match.
**JIRA:**
[ARCHBOM-1357](https://openedx.atlassian.net/browse/ARCHBOM-1357)
**Reviewers:**
finished.
> ARCHBOM-1357: add catch-all to CodeOwnerMetricMiddleware

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/transactions.py
- edx_django_utils/monitoring/utils.py
Adds an `ignore_transaction` utility method. This will allows consuming apps to ignore transaction in views we don't want monitored (like `/health/` checks)
**JIRA:**
No JIRA ticket.
N/A
N/A
N/A
N/A
**Reviewers:**
finished.
> Add ignore transaction util

- CHANGELOG.rst
- README.rst
- edx_django_utils/__init__.py
- edx_django_utils/plugins/__init__.py
- edx_django_utils/plugins/plugin_apps.py
- edx_django_utils/plugins/plugin_contexts.py
- edx_django_utils/plugins/plugin_manager.py
- edx_django_utils/plugins/plugin_settings.py
- edx_django_utils/plugins/plugin_signals.py
- edx_django_utils/plugins/plugin_urls.py
- edx_django_utils/plugins/registry.py
- edx_django_utils/plugins/utils.py
- requirements/constraints.txt
This PR exposes all public functions in edx_django_utils/plugins directory in its __init__.py file.
- this was done to keep inline with standard/pattern used in other packages in edx_django_utils
**JIRA:**
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
>  Adding plugin api in __init__.py

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/middleware.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1970
First we need to merge this and then we can un-pin in edx-platform.
> BOM 1970: Unpin psutils from edx-django-utils

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/code_owner/__init__.py
- edx_django_utils/monitoring/code_owner/middleware.py
- edx_django_utils/monitoring/code_owner/tests/test_middleware.py
- edx_django_utils/monitoring/code_owner/tests/test_utils.py
- edx_django_utils/monitoring/code_owner/utils.py
- edx_django_utils/monitoring/docs/how_tos/using_custom_attributes.rst
* Exposed existing get_code_owner_from_module via the public api.
* Fixed get_code_owner_from_module to not require a call to is_code_owner_mappings_configured beforehand.
* Set the existing code_owner_path_module custom attribute, even for cases where the transaction name was used, rather than the view module.
* Refactored and simplified configuration and tests.
**JIRA:**
[ARCHBOM-1527](https://openedx.atlassian.net/browse/ARCHBOM-1527)
finished.
> ARCHBOM-1527: update code owner mapping

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
- edx_django_utils/monitoring/internal/code_owner/middleware.py
- edx_django_utils/monitoring/internal/code_owner/utils.py
- edx_django_utils/monitoring/tests/code_owner/test_middleware.py
- edx_django_utils/monitoring/tests/code_owner/test_utils.py
* add set_code_owner_attribute decorator for use with celery tasks.
* clean up code owner middleware code.
* rename custom attribute code_owner_path_module to
code_owner_module. This may affect monitoring dashboards.
* minor change in when error custom attributes are set.
**JIRA:**
[ARCHBOM-1260](https://openedx.atlassian.net/browse/ARCHBOM-1260)
**Testing:**
WIP testing in edx-platform https://github.com/edx/edx-platform/pull/25584 (currently failing)
finished.
> ARCHBOM-1260: enable code_owner for celery tasks

- edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
The celery signal task_prerun is a potential
alternative for the decorator. This is being
noted for our future selves, which will also
help clarify that it wasn't yet tried.
**JIRA:**
[ARCHBOM-1636](https://openedx.atlassian.net/browse/ARCHBOM-1636)
finished.~
>  ARCHBOM-1636: add note about task_prerun

- edx_django_utils/monitoring/internal/middleware.py
This PR squashes the following warning (as part of the [Squash a Warning event](https://discuss.openedx.org/t/squash-a-warning-earn-a-badge/3497)):
> edx_django_utils/monitoring/tests/test_middleware.py::TestMonitoringMemoryMiddleware::test_memory_monitoring_when_enabled
>   /home/elrull/workspace/opencraft/edx-django-utils/edx_django_utils/monitoring/internal/middleware.py:180: DeprecationWarning: memory_info_ex() is deprecated and will be removed; use memory_info() instead
>     'ext_memory_info': process.memory_info_ex(),
It can be checked running tests:
make test
> SE-3724: squash warnings

- edx_django_utils/plugins/README.rst
- edx_django_utils/plugins/docs/how_tos/how_to_enable_plugins_for_an_ida.rst
Move notes from JIRA to the repo:
* Explain when INSTALLED_APPS might be preferred.
* Note that unit test coverage is missing.
* Add note about the missing constants for IDAs.
**JIRA:**
[ARCHBOM-1577](https://openedx.atlassian.net/browse/ARCHBOM-1577)
> ARCHBOM-1577: update plugin framework docs

- edx_django_utils/plugins/__init__.py
- edx_django_utils/plugins/pluggable_override.py
- edx_django_utils/tests/test_pluggable_override.py
This adds a new extension point - a `pluggable_override` decorator that allows overriding any function or method by pointing to its alternative implementation in settings.
This ticket is a part of edx/edx-platform#21433 and should be merged before that one.
**JIRA:**
[OSPR-3801](https://openedx.atlassian.net/browse/OSPR-3801)
edx/edx-platform#21433
Before edx/edx-platform#21433.
Listed in edx/edx-platform#21433.
Listed in edx/edx-platform#21433.
**Reviewers:**
finished.
> [BB-933] Add `pluggable_override`

- edx_django_utils/plugins/README.rst
This PR fixes a `Typo` in the example of defining `settings` in a plugin (https://github.com/edx/edx-django-utils/tree/master/edx_django_utils/plugins). And removes all the `u'...'` prefixes from the `README.rst` file.
**JIRA:**
None
None
None
None
1. Go to https://github.com/edx/edx-django-utils/tree/master/edx_django_utils/plugins
2. Check if the fix is applied
**Reviewers:**
finished.
> docs: convert relative_path keyword to string in plugin example and remove 'u' prefixes

- edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
Added plural to code owner custom attributes
to go along with the earlier change. The file name
is not being updated to avoid having to update
incoming links.
**JIRA:**
[ARCHBOM-1551](https://openedx.atlassian.net/browse/ARCHBOM-1551)
> docs: minor update to doc title

- docs/index.rst
- docs/monitoring/README.rst
- docs/monitoring/decisions/0001-monitoring-by-code-owner.rst
- docs/monitoring/decisions/0002-custom-monitoring-language.rst
- docs/monitoring/decisions/0003-code-owner-for-celery-tasks.rst
- docs/monitoring/decisions/0004-code-owner-theme-and-squad.rst
- docs/monitoring/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
- docs/monitoring/how_tos/search_new_relic_nrql.rst
- docs/monitoring/how_tos/update_monitoring_for_squad_or_theme_changes.rst
- docs/monitoring/how_tos/using_custom_attributes.rst
- edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
- edx_django_utils/monitoring/docs/how_tos/search_new_relic_nrql.rst
- edx_django_utils/monitoring/docs/how_tos/update_monitoring_for_squad_or_theme_changes.rst
- edx_django_utils/monitoring/docs/how_tos/using_custom_attributes.rst
*docs: update published doc outline*
Updates the doc index to provide some minor enhancements, and to include the monitoring decisions and how-tos.
See docs/monitoring/README.rst for the decision on how these docs were included.
Here is a screenshot of the new outline:
*docs: refactor squad and theme name change how to*
Extracts the following new how tos:
- search_new_relic_nrql.rst
- update_monitoring_for_squad_or_theme_changes.rst
I'm uncertain about how I included the monitoring docs in the outline, but I didn't wanted to be blocked and I wanted to be able to point to these docs from the runbook.
> update doc outline and extract how tos

- edx_django_utils/monitoring/scripts/new_relic_nrql_search.py
The original search script was using the New Relic REST API
v2, which has gaps and bugs. It was not clearly documented
that the preferred method is to use the new GraphQL API.
The script has been updated to use the new GraphQL API.
Note: it may make sense to introduce Graphene, or some other
library to work with GraphQL, but to start I avoided adding
a new dependency and was able to use New Relic's GUI to play
with different queries here:
https://api.newrelic.com/graphiql
Was tested locally with the following:
```
python edx_django_utils/monitoring/scripts/new_relic_nrql_search.py --regex "'(arch|platform-arch)'"
python edx_django_utils/monitoring/scripts/new_relic_nrql_search.py --regex "'(arch|platform-arch)'" --policy_id 1148306 --policy_id …
```
> fix: NRQL search script using updated api

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/admin/mixins.py
- edx_django_utils/admin/tests/models.py
- edx_django_utils/admin/tests/test_mixins.py
- test_settings.py
The mixin disables CRUD operations on the admin's model. This type of mixin is currently used in an edx-platform Django proxy model, used for invoking actions on certain course keys - but without modifying the proxied model.
Bump version to 4.1.0 for release.
**JIRA:**
https://openedx.atlassian.net/browse/TNL-8080
**Reviewers:**
finished.
> feat: Add read-only mixin for a custom Django admin class

- .github/workflows/upgrade-python-requirements.yml
Updated the upgrade-python-requirements job schedule as we need to run the jobs until 5:00 UTC
> fix: Updated the upgrade job schedule

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/tests/test_monitoring.py
**Issue:** [BOM-2745](https://openedx.atlassian.net/browse/BOM-2745)
- Added `DeploymentMonitoringMiddleware` in monitoring middlewares to save `Python` and `Django` versions as custom attributes in `NewRelic` events.
> BOM-2745: Add DeploymentMonitoringMiddleware

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/tests/code_owner/test_middleware.py
- edx_django_utils/plugins/plugin_urls.py
'django.conf.urls.url' has been deprecated in Django 3 in favour of 'django.urls.re_path'
> chore: Replace deprecated 'django.conf.urls.url'

- CHANGELOG.rst
- edx_django_utils/plugins/plugin_urls.py
`django.conf.urls` has been deprecated in Django 3 in favor of `django.urls`.
> Remove usage of deprecated Django Import

- CHANGELOG.rst
- README.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/scripts/process_cookie_monitoring_logs.py
- edx_django_utils/monitoring/tests/test_custom_monitoring.py
- edx_django_utils/monitoring/tests/test_middleware.py
- requirements/ci.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
Adds CookieMonitoringMiddleware for monitoring cookie header sizes
and cookie sizes. This middleware is being moved from edx-platform:
https://github.com/openedx/edx-platform/blob/master/openedx/core/lib/request_utils.py#L93
Also includes moving the process_cookie_monitoring_logs.py
script to this repository.
**JIRA:**
[ARCHBOM-2054](https://openedx.atlassian.net/browse/ARCHBOM-2054)
finished.
I attempted a consolidated MonitoringMiddleware, but it got messy fast, and would have required a bunch of engineering to keep clean. So for now, we just need to add additional middleware as-needed.
> feat: add CookieMonitoringMiddleware

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/tests/test_middleware.py
- Make independent of other cookie logging; no longer needs to meet cookie
size threshold or sampling rate.
- New setting `UNUSUAL_COOKIE_SAMPLING_LOG_CHUNK` helps avoid truncated
(non-decryptable) messages by splitting the output across multiple log
messages.
**JIRA:**
ref: 2U ARCHBOM-2082
finished.
> feat: Improvements to corrupt cookie logging

- edx_django_utils/plugins/README.rst
This is just a minor fix for docs. Fixing incorrect rst sytanx along with adding the correct redirect link
**Reviewers:**
> docs: fix link to 'how to enable plugins'

- README.rst
The README still lists publishing docs as a TODO,
even though it has already been published.
> docs: remove doc publish todo from readme 

- CHANGELOG.rst
- LICENSE.txt
- README.rst
- edx_django_utils/__init__.py
- setup.py
See discussion on https://github.com/openedx/tcril-engineering/issues/289 for background (and authorization).
> docs: Relicense from AGPL 3 to Apache 2

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/utils.py
- edx_django_utils/monitoring/tests/test_utils.py
We would like to be able to add our own custom handling to background task monitoring, so we added a simple wrapper around it.
> feat: Add wrapper for New Relic's background_task.

- edx_django_utils/user/management/commands/manage_user.py
- edx_django_utils/user/management/tests/test_manage_user.py
JIRA:PSRE-2274
I wanted to see the other email address - not the one logged as email in the yaml file - so this ticket adds a tiny bit of logging to do that. 
**JIRA:**
[PSRE-2274](https://openedx.atlassian.net/browse/PSRE-2274)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> fix: add logging of both emails

- .github/workflows/ci.yml
- edx_django_utils/__init__.py
JIRA:PSRE-2274
This bumps the release version to apply the changes in https://github.com/openedx/edx-django-utils/pull/280
**JIRA:**
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> chore: bump init version for release

- docs/index.rst
- docs/plugins/decisions/0001-plugin-contexts.rst
- docs/plugins/how_tos/how_to_enable_plugins_for_an_ida.rst
- docs/plugins/readme.rst
Adds the plugins docs to the main index. This will make fixing the links in https://github.com/openedx/edx-django-utils/pull/278 easier. It follows the same pattern as was used in the monitoring docs. It's a bit clunky but it does work. See the docs/maintenance README for why this approach was chosen.
> fix: include plugin docs in index

- Makefile
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.in
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.txt
- `pip.txt` wasn't being updated in the `make upgrade` job because the `--upgrade` flag was missing in the `pip-compile` command
- It was causing the scheduled `Python Requirements Upgrade` [build](https://github.com/openedx/edx-django-utils/actions/runs/4847705622/jobs/8666288926#step:5:28) to fail due to `pip & pip-tools` conflict.
> fix: enable updating pip.txt in make upgrade

- .coveragerc
- Closes https://github.com/openedx/edx-django-utils/issues/305
- Correct .coveragerc ``omit`` file paths to properly specify directories.
- Following the instructions in the https://coverage.readthedocs.io/en/7.2.5/migrating.html for the new version.
> fix: fix coveragerc paths format

- .github/dependabot.yml
- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/tests/test_middleware.py
Updates CookieMonitoringMiddleware to remove certain cookies (specified in a setting) from responses. Removes them by setting an expiration date in the past.
**Issue:**
https://github.com/edx/edx-arch-experiments/issues/297
Tested by removing the `experiments_is_enterprise` cookie from CMS (it's set in LMS)
**Reviewers:**
finished.
> feat: remove certain cookies from responses

- edx_django_utils/monitoring/scripts/new_relic_nrql_search.py
New Relic is deprecating their one.nr domain and does not have redirects in place.
> fix: Update New Relic shortlink domain

- .github/workflows/ci.yml
- edx_django_utils/cache/tests/test_middleware.py
- edx_django_utils/monitoring/tests/test_custom_monitoring.py
- edx_django_utils/monitoring/tests/test_middleware.py
- setup.py
- tox.ini
- Add support for  Django 4.2
**Codemod used to upgrade this repo:**  https://github.com/adamchainz/django-upgrade
**Ticket:** https://github.com/edx/upgrades/issues/150
> Django upgrade 4.2

- CHANGELOG.rst
- edx_django_utils/cache/tests/test_utils.py
- edx_django_utils/cache/utils.py
**Description**
- We are replacing [(issue link)](https://github.com/edx/edx-arch-experiments/issues/92) `Python-memcache` with `pymemcache`.
- While doing that [(PR link)](https://github.com/edx/edx-internal/pull/8896) we faced the following error
```
File "/edx/app/edxapp/edx-platform/xmodule/video_block/video_block.py", line 244, in student_view
fragment = Fragment(self.get_html())
File "/edx/app/edxapp/edx-platform/xmodule/video_block/video_block.py", line 355, in get_html
branding_info = BrandingInfoConfig.get_config().get(user_location)
File "/edx/app/edxapp/edx-platform/lms/djangoapps/branding/models.py", line 54, in get_config
return json.loads(info.configuration) if info.enabled else {}
AttributeError: 'NoneType' object has no attribute 'enabled'
```
- The reason for the error is …
> fix: treat none value as cache miss

- edx_django_utils/plugins/docs/how_tos/how_to_create_a_plugin_app.rst
Make it explicit that plugin_app is a required field even if it is empty.
> docs: Hint regarding plugin_app

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/plugins/plugin_apps.py
In edx-platform I found that this doesn't actually log unless I change it to `log.warning`, but... it seems worth changing this in case we get logging levels to work differently during service startup. (If nothing else, the comment may help the next person who is debugging plugins.)
-----
> feat: Change get_plugin_apps to log at info level with more detail

- README.rst
> docs: Replace getting-started instructions with link

- CHANGELOG.rst
- README.rst
- edx_django_utils/data_generation/README.rst
- edx_django_utils/data_generation/management/commands/manufacture_data.py
- edx_django_utils/data_generation/tests/__init__.py
- edx_django_utils/data_generation/tests/apps.py
- edx_django_utils/data_generation/tests/factories.py
- edx_django_utils/data_generation/tests/models.py
- edx_django_utils/data_generation/tests/test_management.py
- requirements/dev.txt
- requirements/doc.in
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- test_settings.py
This change migrates the manufacture_data django command introduced in https://github.com/openedx/edx-enterprise/pull/1826 to where it can be used outside of the enterprise ecosystem.
**JIRA**
[ENT-7636](https://2u-internal.atlassian.net/browse/ENT-7636)
**Installation/Testing instructions:**
***In Devstack, prior to being pushed to PyPi***
1. Copy to IDA VM's python path
Example: `docker cp ~/edx-repos/edx-django-utils/. {container uuid}:/lib/`
Where `container uuid` can be found by running `docker ps`
2. Create management command that inherits from manufacture_data.command and imports model factories (Example: https://github.com/openedx/enterprise-catalog/pull/734)
3. Run manufacture_data management command
Example:
`python ./manage.py manufacture_data --model …
> feat: Add manufacture_data django command

- edx_django_utils/__init__.py
Follow-up from https://github.com/openedx/edx-django-utils/pull/369, where the version didn't get bumped in init.py
> build: bump version

- CHANGELOG.rst
- edx_django_utils/__init__.py
Follow-up from https://github.com/openedx/edx-django-utils/pull/369, where the version didn't get bumped in init.py.  We need to bump it up to 5.10.1 to link to a new version tag to trigger PyPi publishing action.
> build: bump version to 5.10.1

- .github/workflows/ci.yml
- CHANGELOG.rst
- edx_django_utils/__init__.py
- requirements/doc.in
- requirements/doc.txt
- requirements/quality.in
- setup.py
- tox.ini
Python 312 support.
https://github.com/openedx/public-engineering/issues/233
> build: adding 311 support.

- .gitignore
- Makefile
- test_utils/__init__.py
- tests/test_models.py
- tox.ini
- The `tests/__init__.py` create/delete thing seems to have been a workaround for something that's no longer relevant, so just remove it.
- The `test-all` target needed to depend on `clean` so that `build/lib` wouldn't stick around and confuse pytest, and the recipe needed to be pruned down to just `tox` because otherwise we'd run the quality checks twice. (`quality` is in the tox.ini default env list.)
> build: Remove tests/ stub; make `make test-all` work right

- .github/workflows/ci.yml
We've been getting a lot of server errors and rate-limiting issues preventing merges. Until we can get a better option than codecov, let's just prevent it from breaking CI.
> build: Don't fail the build if codecov is having a bad day

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/backends.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/internal/utils.py
- edx_django_utils/monitoring/tests/test_backends.py
- edx_django_utils/monitoring/tests/test_custom_monitoring.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
Switch to pluggable design so that some monitoring functions can report to something other than New Relic. Still defaults to just New Relic, but new setting allows adding OpenTelemetry or Datadog, or removing New Relic.
Initialization and configuration of OpenTelemetry is left as an exercise to the deployer, but https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_otel_monitoring/ would be a likely candidate.
Part of https://github.com/openedx/edx-django-utils/issues/389
> feat: Basic OpenTelemetry and Datadog support

- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/internal/backends.py
Maybe formalize some of this in extras requirements later for better version management.
> docs: Expose telemetry backend requirements in readme

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/tests/test_middleware.py
Add middleware to insert frontend monitoring scripts to response
**Issue:**
https://github.com/edx/edx-arch-experiments/issues/639
**Reviewers:**
finished.
> feat: add middleware to insert frontend moniroting script to response

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- Add default value while getting content-type header to avoid KeyError.
**Reviewers:**
finished.
> fix: add default value while getting content type header

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/tests/test_middleware.py
- This adds the functionality to update Content-Length header if already set to avoid content trimming issue.
- Add waffle switch in frontend monitoring middleware
**Reviewers:**
finished.
> Update Content-Length header in frontend monitoring middleware also adds waffle switch

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/backends.py
- edx_django_utils/monitoring/internal/transactions.py
- edx_django_utils/monitoring/internal/utils.py
**Ticket:**
https://github.com/edx/edx-arch-experiments/issues/658
This adds a new context manager for creating manual spans across our various backends. It adds in an interface for passing through arbitrary backend data because Datadog, New Relic, and OTEL all have different interfaces for creating these spans.
finished.
> feat: Create manual spans for monitoring backends.

- edx_django_utils/plugins/docs/how_tos/how_to_create_a_plugin_app.rst
> docs: Add warning about loading Django settings in plugin apps

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/backends.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/tests/test_custom_monitoring.py
Datadog has issues with tagging the root span
with error information. This change adds the functionality
to tag the root span on exceptions.
This also renames the CachedCustomMonitoringMiddleware into
MonitoringSupportMiddleware so that it can be a central place
for most monitoring middleware changes instead of adding a new
one every time. At some point, CachedCustomMonitoringMiddleware
will be removed.
https://github.com/edx/edx-arch-experiments/issues/647
> feat: Add root span tagging for exceptions.

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/internal/code_owner/utils.py
- edx_django_utils/monitoring/tests/code_owner/test_middleware.py
No code_owner custom attributes should be added
when CODE_OWNER_MAPPINGS is not defined. There
was a bug in both the code and the unit tests.
This has been fixed.
finished.
> fix: bug when CODE_OWNER_MAPPINGS not defined

- CHANGELOG.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- edx_django_utils/monitoring/__init__.py
- edx_django_utils/monitoring/internal/middleware.py
- edx_django_utils/monitoring/signals.py
- edx_django_utils/monitoring/tests/test_monitoring_support.py
Adds signals monitoring_support_process_request,
monitoring_support_process_response, and
monitoring_support_process_exception to the
MonitoringSupportMiddleware to enable plugging in
monitoring capabilities.
finished.
I decided to go with monitoring/signals.py vs monitoring/signals/signals.py to clean up the imports when using the signals, especially given the length of the signal names.
> feat: add monitoring signals for plugins

- edx_django_utils/monitoring/tests/test_monitoring_support.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.txt
Note that we had to update the ddtrace patch mechanism, which was no longer available in the new release.
> chore: upgrade requirements

- .github/CODEOWNERS
This file has been invalid for years.  Just delete it rather than correct it.
> docs: Delete .github/CODEOWNERS

- CHANGELOG.rst
- edx_django_utils/__init__.py
- #496 added Django 5.2 support but the PyPI version release job failed because the version had not been bumped in the `__init__.py` file. 
- Bumping the version to next iteration since the tag `7.3.0` has already been created and can/should not be deleted.
> docs: bump package version to 7.4.0

- CHANGELOG.rst
- README.rst
- edx_django_utils/__init__.py
- edx_django_utils/monitoring/README.rst
- requirements/base.in
- requirements/base.txt
- requirements/test.txt
This will reduce the dependency set for deployers not using New Relic. See DEPR: https://github.com/openedx/public-engineering/issues/360
Also, update docs around choice of backends.
> feat!: Remove newrelic from base dependencies
