CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/cache/README.rst
edx_django_utils/cache/middleware.py
edx_django_utils/cache/tests/test_middleware.py

Rename CacheUtilsMiddleware to RequestCacheMiddleware.
**JIRA:** 
ARCH-177
finished.

ARCH-177: Rename CacheUtilsMiddleware to RequestCacheMiddleware.

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/cache/README.rst
edx_django_utils/cache/middleware.py
edx_django_utils/cache/tests/test_middleware.py

**Description:** 
Split out TieredCacheMiddleware from RequestCacheMiddleware.
**JIRA:**
ARCH-177
finished.
**Author concerns:** List any concerns about this PR - inelegant 

ARCH-177: Split out TieredCacheMiddleware from RequestCacheMiddleware.

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/cache/README.rst
edx_django_utils/cache/tests/test_middleware.py
edx_django_utils/cache/tests/test_utils.py
edx_django_utils/cache/utils.py
edx_django_utils/monitoring/middleware.py

Change is_hit/is_miss to is_found.
Note: I am updating to 1.0.0 because of the breaking change.  No one is using this except ecommerce yet, and I will fix that.
**JIRA:**
[ARCH-223](https://openedx.atlassian.net/browse/ARCH-223)
finished.

ARCH-223: Enhance cache utilities.

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/cache/tests/test_utils.py
edx_django_utils/cache/utils.py

Fix RequestCache thread.local bug.
finished.

Fix RequestCache thread.local bug.

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/cache/tests/test_utils.py
edx_django_utils/cache/utils.py

ARCH-223
Trying to replace https://github.com/edx/edx-django-utils/pull/11 to get codecov to run.
finished.

ARCH-223: Fix RequestCache thread.local bug (take 2).

---

edx_django_utils/__init__.py
edx_django_utils/monitoring/utils.py

Minor fix to comment.  No plans to release this.  Updated version for potential future release.

Minor fix to monitoring usage comment.

---

edx_django_utils/__init__.py
edx_django_utils/monitoring/middleware.py

Moving to edx-drf-extensions: https://github.com/edx/edx-drf-extensions/pull/62
https://openedx.atlassian.net/browse/REVMI-35

Revert "Add user ids to New Relic as a custom parameter."

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Add CODEOWNERS file to enable merge by anyone after review by @edx/arch-review.

add CODEOWNERS file

---

.travis.yml
CHANGELOG.rst
edx_django_utils/__init__.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt
setup.py
tox.ini

Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1554).

Updated the tox and travis configs -- BOM-1554

---

CHANGELOG.rst
edx_django_utils/__init__.py
openedx.yaml
pylintrc
pylintrc_tweaks
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.in
requirements/quality.txt
requirements/test.txt
requirements/travis.txt
setup.py
tox.ini

https://openedx.atlassian.net/browse/BOM-1662
Removing ceninusepy3
update requirements.
Describe in a couple of sentence what this PR adds
**JIRA:**
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.

Removing ceninusepy3 and update requirements.

---

edx_django_utils/monitoring/README.rst
edx_django_utils/monitoring/docs/how_tos/using_custom_metrics.rst

This doc replaces and enhances some of the docs that were in:
https://openedx.atlassian.net/wiki/spaces/PERF/pages/54362736/Custom+Metrics+in+New+Relic
ARCHBOM-1255
FYI: @ormsbee

ARCHBOM-1255: add how-to for custom metrics

---

docs/conf.py
edx_django_utils/__init__.py
edx_django_utils/apps.py
manage.py
setup.py
test_settings.py
tests/test_models.py

removed deprecated `__future__` imports.
**JIRA:**
https://openedx.atlassian.net/browse/BOM-1751
**Reviewers:**
finished.

Removed deprecated future imports

---

CHANGELOG.rst
edx_django_utils/monitoring/README.rst
edx_django_utils/monitoring/code_owner/middleware.py
edx_django_utils/monitoring/code_owner/utils.py
edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_metric_to_an_ida.rst

ARCHBOM-1357
**Post-Merge Communications**
**Reviewers:**
finished.

ARCHBOM-1357: add how_to for CodeOwnerMetricMiddleware

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/plugins/__init__.py
edx_django_utils/plugins/docs/how_tos/how_to_enable_plugins_for_an_ida.rst
edx_django_utils/plugins/plugin_apps.py
edx_django_utils/plugins/plugin_contexts.py
edx_django_utils/plugins/plugin_settings.py
edx_django_utils/plugins/plugin_signals.py
edx_django_utils/plugins/plugin_urls.py
edx_django_utils/plugins/registry.py

Adding more objects to __init__.py api and changing function names to be more descriptive
**JIRA:**
[ARCHBOM-1402](https://openedx.atlassian.net/browse/ARCHBOM-1402)

Changing function names in plugins and adding more objects to api

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/monitoring/middleware.py
edx_django_utils/monitoring/tests/test_monitoring.py

The accumulate method wasn't accumulating, and the unit
test wasn't working as expected.
**JIRA:**
[ARCHBOM-1490](https://openedx.atlassian.net/browse/ARCHBOM-1490)
finished.

ARCHBOM-1490: fix custom monitoring accumulate

---

edx_django_utils/monitoring/README.rst

This README was missed when renaming custom metrics to
custom attributes in an earlier release.
**JIRA:**
[ARCHBOM-1490](https://openedx.atlassian.net/browse/ARCHBOM-1490)
finished.

ARCHBOM-1490: fix README for custom attributes

---

CHANGELOG.rst
edx_django_utils/__init__.py
edx_django_utils/monitoring/README.rst
edx_django_utils/monitoring/__init__.py
edx_django_utils/monitoring/internal/utils.py
edx_django_utils/monitoring/tests/test_monitoring.py
edx_django_utils/monitoring/utils.py

* Add `record_exception` to monitor uncaught exceptions.
* Add additional details to the `deprecated_monitoring_utils`
custom attribute values to make it simpler to track down usage.
finished.

add record_exception and update deprecated custom attribute values

---

CHANGELOG.rst
README.rst

Add a basic development workflow section to the readme.
finished.

Add development workflow docs.

---

edx_django_utils/monitoring/docs/decisions/0003-code-owner-for-celery-tasks.rst
edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
edx_django_utils/monitoring/internal/code_owner/utils.py

See ADR for details, including a possible
future alternative solution.
**JIRA:**
[ARCHBOM-1636](https://openedx.atlassian.net/browse/ARCHBOM-1636)
finished.~

ARCHBOM-1636: add adr for code_owner and celery tasks

---

.github/workflows/ci.yml
CHANGELOG.rst
edx_django_utils/__init__.py
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
setup.py
tox.ini

Dropped the support for python 3.5
**JIRA:**
https://openedx.atlassian.net/browse/BOM-2162

Dropped the support for python 3.5

---

CHANGELOG.rst
edx_django_utils/__init__.py

Update the version number to make pluggable_decorator available to users of this repo.

Bump the version for `pluggable_decorator`

---

CHANGELOG.rst

Fixes minor formatting issues for the 4.0.0
entry in the changelog.
finished.

fix: changelog formatting issues

---

CHANGELOG.rst
edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst
edx_django_utils/monitoring/scripts/new_relic_nrql_search.py

Updated the no-longer-needed new_relic_code_owner_audit.py to be a new `new_relic_nrql_search.py` script, which searches the NRQL in New Relic alert policies and dashboards for the provided regex. Use --help for details.
Also, added documentation for updating squad and theme names.

feat: new relic NRQL search script

---

edx_django_utils/monitoring/scripts/new_relic_nrql_search.py

The dashboard list query returns both dashboards and dashboard page
entities, but the dashboard entity query only works with dashboards,
not dashboard pages. This refactor filters these results, rather
than making the second API call and skipping when it has an error.

refactor: filter dashboard pages

---

edx_django_utils/monitoring/scripts/new_relic_nrql_search.py

Adds links to the search results. For alert policies, we do not
have the direct link, so the same static link to the alert policy
home page is included with each result. For dashboards, a permalink
is included.
**JIRA:**
?

feat: add links for search results

---

edx_django_utils/plugins/README.rst

Update README to be a little more explicit on how to create new plugins
**JIRA:**
[ARCHBOM-2040](https://openedx.atlassian.net/browse/ARCHBOM-2040)
**Reviewers:**
finished.

docs: update README with more explicit directions for new plugins

---

edx_django_utils/plugins/README.rst

Just fixing a syntax/typo in Readme
**JIRA:**
instructions.
Just replicate this:
> Then, open a shell using ``./manage.py lms shell`` and run::
```
>>> from django.apps import apps
>>> [app.verbose_name for app  in apps.get_app_configs()]
```
**Reviewers:**
finished.

fix: fix syntax error in code snippet

---

CHANGELOG.rst
edx_django_utils/monitoring/internal/middleware.py
edx_django_utils/monitoring/tests/test_middleware.py

Log headers (encrypted) if large/sampled cookies appear corrupted.
Enabled if encryption key is set in IDA.
**JIRA:**
[ARCHBOM-2082](https://openedx.atlassian.net/browse/ARCHBOM-2082)
finished.

feat: Log headers (encrypted) if large/sampled cookies appear corrupted

---

CHANGELOG.rst
edx_django_utils/__init__.py

chore: Bump version to 4.8.1 (4.8.0 was a misfire)

---

CHANGELOG.rst
edx_django_utils/__init__.py

I realized while writing the release notes that I hadn't captured
everything in the changelog and that there was technically a breaking
change.
finished.

docs: Add missing notes to changelog; bump major version

---

edx_django_utils/plugins/docs/how_tos/how_to_enable_plugins_for_an_ida.rst

Add clarification that this how-to for enabling
plugins in an IDA is a one-time setup.

docs: explain when plugin how-to is needed

---

CHANGELOG.rst
README.rst
edx_django_utils/__init__.py
edx_django_utils/ip/README.rst
edx_django_utils/ip/__init__.py
edx_django_utils/ip/internal/ip.py
edx_django_utils/ip/internal/tests/test_ip.py
tox.ini

This will allow using the code in all IDAs.
Part of <https://github.com/openedx/edx-django-utils/issues/241>.
Code will be removed from edx-platform in <https://github.com/openedx/edx-platform/pull/31000>.
----
Commits best reviewed separately.
----

feat: Move safe IP address handling code from edx-platform

---

.github/workflows/upgrade-python-requirements.yml
README.rst
catalog-info.yaml

Added catalog-info.yml, maintainership status badge in the readme, and a default statement into .github/workflows/upgrade-python-requirements.yml to make it better match the template.
**Issue:**
https://github.com/openedx/edx-django-utils/issues/255
**Reviewers:**
- [N/A] Version bumped
- [N/A] Changelog record added
- [N/A] Create a tag
- [N/A] Check new version is pushed to PyPi after tag-triggered build is
finished.

chore: maintainership phase 1 tasks

---

README.rst

Update the README to bring it inline with https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html
**Issue:**
https://github.com/openedx/edx-django-utils/issues/255
**Reviewers:**
- [N/A ] Version bumped
- [ N/A] Changelog record added
- [N/A ] Create a tag
- [N/A ] Check new version is pushed to PyPi after tag-triggered build is
finished.

docs: update README for maintainership pilot

---

edx_django_utils/monitoring/scripts/process_cookie_monitoring_logs.py

Update the process_cookie_monitoring_logs.py script to process log lines with multiple lists of cookie sizes. The difference doesn't turn out to be huge, mostly in total counts, but I think it's a simple enough fix that it's worth putting in so we get more complete data.
**Issue:**
https://github.com/edx/edx-arch-experiments/issues/151
**Reviewers:**
finished.

feat: process logs with >1 cookie section

---

edx_django_utils/plugins/docs/how_tos/how_to_create_a_plugin_app.rst

Add a link to how to install a plugin privately.

docs: Add documentation link for adding private requirements.

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.txt
requirements/test.txt

- latest `pip==23.1` fails with `pip-tools<6.13.0` so updated `pip-tools==6.13.0`.

fix: update pip-tools to 6.13.0

---

CHANGELOG.rst
edx_django_utils/__init__.py

Update package version for django 4.2 support
Ticket: https://github.com/edx/upgrades/issues/150

Update package version for django 4.2 support

---

CHANGELOG.rst
edx_django_utils/cache/tests/test_utils.py
edx_django_utils/cache/utils.py

TieredCache now correctly can cache a None in
either of its two tiers.

fix: TieredCache and cached None

---

edx_django_utils/cache/tests/test_utils.py

**Description**
- Fixed misplaced docstring.

fix: fix misplaced docstring

---

CHANGELOG.rst
edx_django_utils/__init__.py

Releasing new version on pypi.

build: bump package version

---

edx_django_utils/__init__.py

- Update package version number.
- `Changelog` has already been updated in this [PR#363](https://github.com/openedx/edx-django-utils/pull/363)

chore: update package version

---

catalog-info.yaml

Describe in a couple of sentence what this PR adds
**JIRA:**
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.

chore: update arch-bom team name
